// @generated by packages/protocol/scripts/gen-rust.ts — DO NOT EDIT.
//
// Regenerate with `bun run protocol:gen`. CI fails if this file is out of date
// with the zod schemas in packages/protocol/src, so a wire-contract change can
// never reach a provider as a silent no-op.

use serde::{Deserialize, Serialize};

/// Binary video frame type byte, sent as the first byte of each session-plane
/// binary frame.
pub const AU_KEY: u8 = 0;
pub const AU_DELTA: u8 = 1;
pub const AU_KEY_RESET: u8 = 2;

pub const PROTOCOL_VERSION: i64 = 1;

/// Where the coordinator publishes the Ed25519 key session tokens are signed
/// with. Each provider fetches this once at startup and caches it.
pub const JWKS_PATH: &str = "/.well-known/farm-jwks.json";

/// Session tokens must carry this audience; anything else is rejected.
pub const SESSION_TOKEN_AUDIENCE: &str = "farm-provider";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Platform {
    #[serde(rename = "ios")]
    Ios,
    #[serde(rename = "android")]
    Android,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum DeviceStatus {
    #[serde(rename = "absent")]
    Absent,
    #[serde(rename = "present")]
    Present,
    #[serde(rename = "preparing")]
    Preparing,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "busy")]
    Busy,
    #[serde(rename = "unhealthy")]
    Unhealthy,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Display {
    pub width: i64,
    pub height: i64,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub scale: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub rotation: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Battery {
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub level: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub state: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeviceSnapshot {
    pub id: String,
    pub platform: Platform,
    pub status: DeviceStatus,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub manufacturer: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub os_version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub abi: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub sdk: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub display: Option<Display>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub battery: Option<Battery>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub stream_codec: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub adb_port: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub note: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AppInfo {
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub system: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum CommandPayload {
    #[serde(rename = "session.authorize", rename_all = "camelCase")]
    SessionAuthorize {
        device_id: String,
        reservation_id: String,
        user_id: String,
    },
    #[serde(rename = "session.revoke", rename_all = "camelCase")]
    SessionRevoke {
        device_id: String,
        #[serde(skip_serializing_if = "Option::is_none", default)]
        reason: Option<String>,
    },
    #[serde(rename = "device.reboot", rename_all = "camelCase")]
    DeviceReboot { device_id: String },
    #[serde(rename = "device.rotate", rename_all = "camelCase")]
    DeviceRotate { device_id: String, degrees: i64 },
    #[serde(rename = "device.apps", rename_all = "camelCase")]
    DeviceApps { device_id: String },
    #[serde(rename = "device.launch", rename_all = "camelCase")]
    DeviceLaunch {
        device_id: String,
        app_id: String,
        #[serde(skip_serializing_if = "Option::is_none", default)]
        args: Option<Vec<String>>,
    },
    #[serde(rename = "device.uninstall", rename_all = "camelCase")]
    DeviceUninstall { device_id: String, app_id: String },
    #[serde(rename = "device.adb.expose", rename_all = "camelCase")]
    DeviceAdbExpose { device_id: String },
    #[serde(rename = "device.adb.unexpose", rename_all = "camelCase")]
    DeviceAdbUnexpose { device_id: String },
    #[serde(rename = "device.restart", rename_all = "camelCase")]
    DeviceRestart { device_id: String },
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CommandData {
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub apps: Option<Vec<AppInfo>>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub adb_port: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum ProviderMessage {
    #[serde(rename = "hello", rename_all = "camelCase")]
    Hello {
        protocol_version: i64,
        provider_id: String,
        name: String,
        version: String,
        public_base_url: String,
        #[serde(skip_serializing_if = "Option::is_none", default)]
        hostname: Option<String>,
        devices: Vec<DeviceSnapshot>,
    },
    #[serde(rename = "heartbeat", rename_all = "camelCase")]
    Heartbeat { at: i64 },
    #[serde(rename = "device.upsert", rename_all = "camelCase")]
    DeviceUpsert { device: DeviceSnapshot },
    #[serde(rename = "device.removed", rename_all = "camelCase")]
    DeviceRemoved { device_id: String },
    #[serde(rename = "device.status", rename_all = "camelCase")]
    DeviceStatus {
        device_id: String,
        status: DeviceStatus,
        #[serde(skip_serializing_if = "Option::is_none", default)]
        note: Option<String>,
    },
    #[serde(rename = "device.display", rename_all = "camelCase")]
    DeviceDisplay { device_id: String, display: Display },
    #[serde(rename = "device.battery", rename_all = "camelCase")]
    DeviceBattery { device_id: String, battery: Battery },
    #[serde(rename = "command.result", rename_all = "camelCase")]
    CommandResult {
        id: String,
        ok: bool,
        #[serde(skip_serializing_if = "Option::is_none", default)]
        error: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none", default)]
        data: Option<CommandData>,
    },
    #[serde(rename = "install.finished", rename_all = "camelCase")]
    InstallFinished {
        device_id: String,
        user_id: String,
        filename: String,
        size: i64,
        sha256: String,
        ok: bool,
        #[serde(skip_serializing_if = "Option::is_none", default)]
        error: Option<String>,
    },
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum CoordinatorMessage {
    #[serde(rename = "hello.ack", rename_all = "camelCase")]
    HelloAck {
        protocol_version: i64,
        heartbeat_interval_ms: i64,
        jwks_url: String,
        issuer: String,
        web_origins: Vec<String>,
    },
    #[serde(rename = "hello.reject", rename_all = "camelCase")]
    HelloReject { reason: String },
    #[serde(rename = "command", rename_all = "camelCase")]
    Command { id: String, payload: CommandPayload },
    #[serde(rename = "ping", rename_all = "camelCase")]
    Ping { at: i64 },
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PointerPoint {
    pub x: f64,
    pub y: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum ClientMessage {
    #[serde(rename = "pointer.down", rename_all = "camelCase")]
    PointerDown { pointer_id: i64, at: PointerPoint },
    #[serde(rename = "pointer.move", rename_all = "camelCase")]
    PointerMove { pointer_id: i64, at: PointerPoint },
    #[serde(rename = "pointer.up", rename_all = "camelCase")]
    PointerUp { pointer_id: i64, at: PointerPoint },
    #[serde(rename = "key", rename_all = "camelCase")]
    Key { key: String, down: bool },
    #[serde(rename = "text", rename_all = "camelCase")]
    Text { text: String },
    #[serde(rename = "clipboard.get", rename_all = "camelCase")]
    ClipboardGet,
    #[serde(rename = "clipboard.set", rename_all = "camelCase")]
    ClipboardSet { text: String },
    #[serde(rename = "rotate", rename_all = "camelCase")]
    Rotate { degrees: i64 },
    #[serde(rename = "keyframe", rename_all = "camelCase")]
    Keyframe,
    #[serde(rename = "pong", rename_all = "camelCase")]
    Pong { at: i64 },
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum ServerMessage {
    #[serde(rename = "codec", rename_all = "camelCase")]
    Codec {
        codec: String,
        #[serde(skip_serializing_if = "Option::is_none", default)]
        description: Option<String>,
        display: Display,
    },
    #[serde(rename = "display", rename_all = "camelCase")]
    Display { display: Display },
    #[serde(rename = "clipboard", rename_all = "camelCase")]
    Clipboard {
        #[serde(default)]
        text: Option<String>,
    },
    #[serde(rename = "install.progress", rename_all = "camelCase")]
    InstallProgress {
        #[serde(skip_serializing_if = "Option::is_none", default)]
        progress: Option<f64>,
        stage: String,
    },
    #[serde(rename = "install.result", rename_all = "camelCase")]
    InstallResult {
        ok: bool,
        #[serde(skip_serializing_if = "Option::is_none", default)]
        app_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none", default)]
        error: Option<String>,
    },
    #[serde(rename = "session.closed", rename_all = "camelCase")]
    SessionClosed { reason: String },
    #[serde(rename = "error", rename_all = "camelCase")]
    Error { message: String },
    #[serde(rename = "ping", rename_all = "camelCase")]
    Ping { at: i64 },
}
