/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SessionRouteImport } from './routes/_session'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppProvidersRouteImport } from './routes/_app/providers'
import { Route as AppAdminProvidersRouteImport } from './routes/_app/admin.providers'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin.users'
import { Route as AppDevicesIndexRouteImport } from './routes/_app/devices.index'
import { Route as AppDevicesDeviceIdRouteImport } from './routes/_app/devices.$deviceId'
import { Route as SessionDevicesDeviceIdPopoutRouteImport } from './routes/_session/devices.$deviceId.popout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/_session',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProvidersRoute = AppProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminProvidersRoute = AppAdminProvidersRouteImport.update({
  id: '/admin/providers',
  path: '/admin/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesIndexRoute = AppDevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesDeviceIdRoute = AppDevicesDeviceIdRouteImport.update({
  id: '/devices/$deviceId',
  path: '/devices/$deviceId',
  getParentRoute: () => AppRoute,
} as any)
const SessionDevicesDeviceIdPopoutRoute =
  SessionDevicesDeviceIdPopoutRouteImport.update({
    id: '/devices/$deviceId/popout',
    path: '/devices/$deviceId/popout',
    getParentRoute: () => SessionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/providers': typeof AppProvidersRoute
  '/admin/providers': typeof AppAdminProvidersRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/devices/$deviceId': typeof AppDevicesDeviceIdRoute
  '/devices/': typeof AppDevicesIndexRoute
  '/devices/$deviceId/popout': typeof SessionDevicesDeviceIdPopoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/providers': typeof AppProvidersRoute
  '/admin/providers': typeof AppAdminProvidersRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/devices/$deviceId': typeof AppDevicesDeviceIdRoute
  '/devices': typeof AppDevicesIndexRoute
  '/devices/$deviceId/popout': typeof SessionDevicesDeviceIdPopoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_session': typeof SessionRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/providers': typeof AppProvidersRoute
  '/_app/admin/providers': typeof AppAdminProvidersRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/devices/$deviceId': typeof AppDevicesDeviceIdRoute
  '/_app/devices/': typeof AppDevicesIndexRoute
  '/_session/devices/$deviceId/popout': typeof SessionDevicesDeviceIdPopoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/providers'
    | '/admin/providers'
    | '/admin/users'
    | '/devices/$deviceId'
    | '/devices/'
    | '/devices/$deviceId/popout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/providers'
    | '/admin/providers'
    | '/admin/users'
    | '/devices/$deviceId'
    | '/devices'
    | '/devices/$deviceId/popout'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_session'
    | '/login'
    | '/_app/providers'
    | '/_app/admin/providers'
    | '/_app/admin/users'
    | '/_app/devices/$deviceId'
    | '/_app/devices/'
    | '/_session/devices/$deviceId/popout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SessionRoute: typeof SessionRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_session': {
      id: '/_session'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/providers': {
      id: '/_app/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AppProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/providers': {
      id: '/_app/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AppAdminProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices/': {
      id: '/_app/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof AppDevicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices/$deviceId': {
      id: '/_app/devices/$deviceId'
      path: '/devices/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof AppDevicesDeviceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_session/devices/$deviceId/popout': {
      id: '/_session/devices/$deviceId/popout'
      path: '/devices/$deviceId/popout'
      fullPath: '/devices/$deviceId/popout'
      preLoaderRoute: typeof SessionDevicesDeviceIdPopoutRouteImport
      parentRoute: typeof SessionRoute
    }
  }
}

interface AppRouteChildren {
  AppProvidersRoute: typeof AppProvidersRoute
  AppAdminProvidersRoute: typeof AppAdminProvidersRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppDevicesDeviceIdRoute: typeof AppDevicesDeviceIdRoute
  AppDevicesIndexRoute: typeof AppDevicesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProvidersRoute: AppProvidersRoute,
  AppAdminProvidersRoute: AppAdminProvidersRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppDevicesDeviceIdRoute: AppDevicesDeviceIdRoute,
  AppDevicesIndexRoute: AppDevicesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SessionRouteChildren {
  SessionDevicesDeviceIdPopoutRoute: typeof SessionDevicesDeviceIdPopoutRoute
}

const SessionRouteChildren: SessionRouteChildren = {
  SessionDevicesDeviceIdPopoutRoute: SessionDevicesDeviceIdPopoutRoute,
}

const SessionRouteWithChildren =
  SessionRoute._addFileChildren(SessionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SessionRoute: SessionRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
